import { useState } from 'react';
import { createDepartment, deleteDepartment } from '../services/api';

const BASE_FILTERS = [
  { name: 'all', label: 'All', description: 'Show all emails' },
  { name: 'trusted', label: 'Trusted', description: 'Emails from trusted senders' },
  { name: 'spam', label: 'Spam', description: 'Emails classified as spam' },
  { name: 'ignored', label: 'Ignored', description: 'Emails marked as ignored (newsletters, etc.)' },
  { name: 'read', label: 'Read', description: 'Emails already read' },
];

const BUILTIN_DEPT_FILTERS = [
  { name: 'ventas', label: 'Ventas', description: 'Presupuestos, cotizaciones, propuestas comerciales y consultas de clientes nuevos' },
  { name: 'administracion', label: 'Administración', description: 'Facturas, pagos, recibos, tesorería y gestión contable' },
  { name: 'soporte_tecnico', label: 'Soporte Técnico', description: 'Solicitudes de asistencia técnica, configuraciones y diagnósticos' },
];

export default function FilterBar({
  filterClass,
  filterDomain,
  filterMonth,
  filterYear,
  onClassChange,
  onDomainChange,
  onMonthChange,
  onYearChange,
  onClear,
  clearLoading,
  clearError,
  departments = [],
  onDepartmentsChange,
  onEmailsReclassified,
  counts = {},
  accountId,
}) {
  const [areasOpen, setAreasOpen] = useState(true);
  const [adding, setAdding] = useState(false);
  const [newDeptLabel, setNewDeptLabel] = useState('');
  const [newDeptDescription, setNewDeptDescription] = useState('');
  const [newDeptKeywords, setNewDeptKeywords] = useState('');
  const [deptError, setDeptError] = useState(null);
  const [deletingId, setDeletingId] = useState(null);
  const [addDeptFeedback, setAddDeptFeedback] = useState(null);
  const feedbackTimerRef = useState(null);

  // Auto-generate internal name from label
  const autoGeneratedName = newDeptLabel.trim()
    ? newDeptLabel.trim().toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '')
    : '';

  // Map custom departments to class format (preserve color from DB)
  const customClasses = departments.map(d => ({
    name: d.name,
    label: d.label,
    description: d.description || `Emails classified as ${d.label}`,
    isCustom: true,
    color: d.color || null
  }));

  // All area filters (built-in + custom), deduplicated by name
  // Built-in names take priority; custom departments with the same name are excluded
  const builtinNames = new Set(BUILTIN_DEPT_FILTERS.map(f => f.name));
  const uniqueCustom = customClasses.filter(c => !builtinNames.has(c.name));
  // Also deduplicate among custom classes themselves (defensive against DB duplicates)
  const seenCustom = new Set();
  const dedupedCustom = uniqueCustom.filter(c => {
    if (seenCustom.has(c.name)) return false;
    seenCustom.add(c.name);
    return true;
  });
  const areaClasses = [...BUILTIN_DEPT_FILTERS, ...dedupedCustom];

  function getClassInfo(name, source) {
    const fromSrc = source.find(d => d.name === name);
    if (fromSrc) return fromSrc;
    const dept = departments.find(d => d.name === name);
    if (dept) return { name: dept.name, label: dept.label, description: dept.description || `Emails classified as ${dept.label}` };
    return { name, label: name.charAt(0).toUpperCase() + name.slice(1), description: '' };
  }

  function getCount(name) {
    return counts[name] || 0;
  }

  async function handleAddDept(e) {
    e.preventDefault();
    if (!newDeptLabel.trim()) return;
    setDeptError(null);
    setAddDeptFeedback(null);
    try {
      const keywords = newDeptKeywords.trim()
        ? newDeptKeywords.split(',').map(k => k.trim().toLowerCase()).filter(Boolean)
        : [];
      const result = await createDepartment(autoGeneratedName, newDeptLabel.trim(), newDeptDescription.trim(), keywords, accountId);
      setNewDeptLabel('');
      setNewDeptDescription('');
      setNewDeptKeywords('');
      setAdding(false);
      if (onDepartmentsChange) onDepartmentsChange();

      // Refresh emails and counts since some may have been reclassified
      if (onEmailsReclassified) {
        await onEmailsReclassified();
      }

      if (result && result.reclassifiedCount > 0) {
        setAddDeptFeedback(
          `✓ Departamento creado. ${result.reclassifiedCount} correos existentes fueron asignados automáticamente.`
        );
      } else {
        setAddDeptFeedback('✓ Departamento creado.');
      }

      // Auto-clear feedback after 8 seconds
      if (feedbackTimerRef.current) clearTimeout(feedbackTimerRef.current);
      feedbackTimerRef.current = setTimeout(() => setAddDeptFeedback(null), 8000);
    } catch (err) {
      setDeptError(err.message || 'Error al agregar departamento');
    }
  }

  async function handleDeleteDept(id) {
    if (!window.confirm('Delete this department filter?')) return;
    setDeletingId(id);
    setDeptError(null);
    try {
      await deleteDepartment(id);
      if (onDepartmentsChange) onDepartmentsChange();
    } catch (err) {
      setDeptError(err.message);
    } finally {
      setDeletingId(null);
    }
  }

  const helpTooltipText = "Los filtros organizan tus correos por departamento. Podés crear nuevos departamentos con el botón + Dept y asignarles palabras clave para clasificación automática.";

  function renderFilterButton(c, source) {
    const info = getClassInfo(c.name, source);
    const count = getCount(c.name);
    return (
      <label
        key={c.name}
        className={`radio-label${filterClass === c.name ? ' active' : ''}`}
        title={info.description}
      >
        <input
          type="radio"
          name="classification"
          value={c.name}
          checked={filterClass === c.name}
          onChange={() => onClassChange(c.name)}
        />
        <span className="filter-label-text">
          {info.color && (
            <span
              style={{
                display: 'inline-block',
                width: 8,
                height: 8,
                borderRadius: '50%',
                backgroundColor: info.color,
                marginRight: 4,
                verticalAlign: 'middle',
              }}
              title="Departamento creado por el usuario"
            />
          )}
          {info.label}
          {count > 0 && <span className="filter-count-badge">{count}</span>}
        </span>
        {c.isCustom && (
          <button
            className="dept-remove-btn"
            title="Remove this department"
            onClick={(e) => {
              e.preventDefault();
              e.stopPropagation();
              const dept = departments.find(d => d.name === c.name);
              if (dept) handleDeleteDept(dept.id);
            }}
            disabled={deletingId === (departments.find(d => d.name === c.name)?.id)}
          >
            ×
          </button>
        )}
      </label>
    );
  }

  return (
    <div className="filter-bar">
      <div className="filter-bar-row filter-row">
        {/* GROUP 1 — Default filters */}
        <div className="filter-group">
          <span className="filter-label">
            Filter:
            <span className="filter-help-icon" title={helpTooltipText}>ⓘ</span>
          </span>
          <div className="radio-group">
            {BASE_FILTERS.map((c) => renderFilterButton(c, BASE_FILTERS))}
          </div>
        </div>

        {/* Vertical divider */}
        <div className="filter-divider" />

        {/* GROUP 2 — Areas toggle */}
        <div className="filter-group areas-wrapper">
          <button
            className="areas-toggle"
            onClick={() => setAreasOpen(v => !v)}
            title="Toggle department/area filters"
          >
            Áreas
            <span className={`areas-arrow${areasOpen ? ' areas-arrow-open' : ''}`}>▾</span>
          </button>

          {areasOpen && (
            <div className="areas-group">
              {areaClasses.map((c) => renderFilterButton(c, areaClasses))}
              <button
                className="btn btn-secondary btn-xs"
                onClick={() => setAdding(!adding)}
                title="Create a new department filter with keywords for automatic classification"
              >
                {adding ? 'Cancel' : '+ Dept'}
              </button>
            </div>
          )}
        </div>

        {/* Domain text filter (live, client-side) */}
        <div className="filter-group">
          <span className="filter-label">Domain:</span>
          <input
            type="text"
            className="input input-sm"
            style={{ width: 180 }}
            placeholder="Filter by domain..."
            value={filterDomain}
            onChange={(e) => onDomainChange(e.target.value)}
          />
        </div>

        {/* Date filter: month + year */}
        <div className="filter-group">
          <span className="filter-label">Date:</span>
          <select value={filterMonth || ''} onChange={(e) => onMonthChange(e.target.value)} className="input input-sm" style={{width:110}}>
            <option value="">All months</option>
            <option value="4">Apr</option>
            <option value="5">May</option>
            <option value="6">Jun</option>
          </select>
          <select value={filterYear || '2026'} onChange={(e) => onYearChange(e.target.value)} className="input input-sm" style={{width:110, marginLeft:8}}>
            <option value="2026">2026</option>
          </select>
        </div>

        {/* Clear database action */}
        <div className="filter-actions">
          <button
            className="btn btn-danger btn-sm"
            onClick={onClear}
            disabled={clearLoading}
          >
            {clearLoading ? 'Clearing...' : 'Clear database'}
          </button>
          {clearError && <span className="error-msg">{clearError}</span>}
        </div>
      </div>

      {/* Add department form */}
      {adding && (
        <form className="add-dept-form" onSubmit={handleAddDept}>
          <div className="add-dept-field">
            <label className="add-dept-label">Department display name *</label>
            <input
              type="text"
              className="input input-sm"
              placeholder="e.g. Recursos Humanos"
              value={newDeptLabel}
              onChange={(e) => setNewDeptLabel(e.target.value)}
              style={{ width: 280 }}
              required
            />
            {autoGeneratedName && (
              <span className="add-dept-hint">Internal name: <strong>{autoGeneratedName}</strong></span>
            )}
          </div>
          <div className="add-dept-field">
            <label className="add-dept-label">Description (optional)</label>
            <input
              type="text"
              className="input input-sm"
              placeholder="¿Qué emails van aquí?"
              value={newDeptDescription}
              onChange={(e) => setNewDeptDescription(e.target.value)}
              style={{ width: 280 }}
            />
          </div>
          <div className="add-dept-field">
            <label className="add-dept-label">Keywords (optional)</label>
            <textarea
              className="input input-sm"
              placeholder="Palabras clave separadas por coma: soporte, técnico, falla..."
              value={newDeptKeywords}
              onChange={(e) => setNewDeptKeywords(e.target.value)}
              style={{ width: 280, minHeight: 60, resize: 'vertical' }}
            />
          </div>
          <div className="add-dept-actions">
            <button type="submit" className="btn btn-primary btn-sm">Add Department</button>
            {deptError && (
              <p style={{ color: 'var(--error, #ff6b6b)', fontSize: '13px', marginTop: '6px' }}>
                {deptError}
              </p>
            )}
            {addDeptFeedback && (
              <p style={{ color: '#43d17a', fontSize: '13px', marginTop: '6px' }}>
                {addDeptFeedback}
              </p>
            )}
          </div>
        </form>
      )}
    </div>
  );
}